import React, { useState, useEffect, useMemo } from "react";
import { IconPrinter, IconSearch, IconMapPin, IconShare2, IconQrCode, IconChevronLeft, IconChevronRight, ResourceType, KALASIN_LOCATIONS } from "../constants";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";
import Swal from "sweetalert2";

    const DashboardTab = ({ resources }) => {
      const [filterDistrict, setFilterDistrict] = useState('all');
      const [filterSubDistrict, setFilterSubDistrict] = useState('all');
      const [searchQuery, setSearchQuery] = useState('');
      const [currentPage, setCurrentPage] = useState(1);
      const [isPrinting, setIsPrinting] = useState(false);
      const [showComparison, setShowComparison] = useState(false);
      const itemsPerPage = 10;
      const COLORS = ['#7c3aed', '#f59e0b', '#ec4899'];
      if (!BarChart || !PieChart) return <div className="p-12 text-center text-purple-500 bg-white rounded-3xl shadow-lg border border-purple-50">กำลังโหลดกราฟ...</div>;
      const filteredData = useMemo(() => { let data = resources; if (filterDistrict !== 'all') data = data.filter(r => r.district === filterDistrict); if (filterSubDistrict !== 'all') data = data.filter(r => r.subDistrict === filterSubDistrict); if (searchQuery.trim()) { const q = searchQuery.trim().toLowerCase(); data = data.filter(r => r.name.toLowerCase().includes(q) || (r.description && r.description.toLowerCase().includes(q)) || (r.contactInfo && r.contactInfo.includes(q))); } return data; }, [resources, filterDistrict, filterSubDistrict, searchQuery]);
      const comparisonData = useMemo(() => { return KALASIN_LOCATIONS.map(loc => { const dItems = resources.filter(r => r.district === loc.district); const shortName = loc.district.replace('สกร.ระดับอำเภอ', ''); const person = dItems.filter(r => r.type === ResourceType.PERSON).length; const innovation = dItems.filter(r => r.type === ResourceType.INNOVATION).length; const place = dItems.filter(r => r.type === ResourceType.PLACE).length; return { name: shortName, total: dItems.length, person, innovation, place, subDistrictCount: loc.subDistricts.length, coverage: loc.subDistricts.filter(sd => dItems.some(r => r.subDistrict === sd)).length }; }).sort((a, b) => b.total - a.total); }, [resources]);
      const subDistrictData = useMemo(() => { if (filterDistrict === 'all') return []; const dItems = filteredData; const counts = {}; dItems.forEach(r => { const shortSub = r.subDistrict.replace('ศกร.ระดับตำบล', ''); counts[shortSub] = (counts[shortSub] || 0) + 1; }); const found = KALASIN_LOCATIONS.find(d => d.district === filterDistrict); if (found) { found.subDistricts.forEach(sd => { const shortSub = sd.replace('ศกร.ระดับตำบล', ''); if (!counts[shortSub]) counts[shortSub] = 0; }); } return Object.keys(counts).map(key => ({ name: key, value: counts[key] })).sort((a, b) => b.value - a.value); }, [filteredData, filterDistrict]);
      useEffect(() => { setCurrentPage(1); }, [filteredData]);
      const indexOfLastItem = currentPage * itemsPerPage;
      const indexOfFirstItem = indexOfLastItem - itemsPerPage;
      const currentItems = isPrinting ? filteredData : filteredData.slice(indexOfFirstItem, indexOfLastItem);
      const totalPages = Math.ceil(filteredData.length / itemsPerPage);
      const typeData = useMemo(() => { const counts = {}; Object.values(ResourceType).forEach(t => counts[t] = 0); filteredData.forEach(r => { if (counts[r.type] !== undefined) counts[r.type]++; }); return Object.keys(counts).map(key => ({ name: key.replace('แหล่งเรียนรู้ประเภท', ''), fullName: key, value: counts[key] })); }, [filteredData]);
      const districtData = useMemo(() => { const counts = {}; KALASIN_LOCATIONS.forEach(d => { const shortName = d.district.replace('สกร.ระดับอำเภอ', ''); counts[shortName] = 0; }); filteredData.forEach(r => { const shortName = r.district.replace('สกร.ระดับอำเภอ', ''); counts[shortName] = (counts[shortName] || 0) + 1; }); return Object.keys(counts).map(key => ({ name: key, value: counts[key] })).sort((a, b) => b.value - a.value); }, [filteredData]);
      const availableSubDistricts = useMemo(() => { if (filterDistrict === 'all') return []; const found = KALASIN_LOCATIONS.find(d => d.district === filterDistrict); return found ? found.subDistricts : []; }, [filterDistrict]);
      const handlePrint = () => { setIsPrinting(true); setTimeout(() => { window.print(); setIsPrinting(false); }, 500); };
      const goToPage = (page) => { if (page >= 1 && page <= totalPages) setCurrentPage(page); };
      const handleShare = (resource) => { const googleMapsUrl = `https://www.google.com/maps/search/?api=1&query=${resource.latitude},${resource.longitude}`; const text = `แนะนำแหล่งเรียนรู้: ${resource.name}\n📍 ${resource.subDistrict}, ${resource.district}`; if (navigator.share) { navigator.share({ title: 'Kalasin Learning T-Map', text: text, url: googleMapsUrl }).catch(console.error); } else { Swal.fire({ title: 'แชร์พิกัดนำทาง', html: `<div class="p-2 space-y-4"><button onclick="navigator.clipboard.writeText('${googleMapsUrl}'); Swal.fire('คัดลอกลิงก์แผนที่แล้ว','','success')" class="w-full bg-purple-700 text-white p-3 rounded-xl font-bold shadow-lg">คัดลอกลิงก์ Google Maps</button></div>`, showConfirmButton: false, showCloseButton: true }); } };
      const showQRCode = (resource) => { const googleMapsUrl = `https://www.google.com/maps/search/?api=1&query=${resource.latitude},${resource.longitude}`; const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(googleMapsUrl)}`; Swal.fire({ html: `<div class="flex flex-col items-center pt-2"><h3 class="text-xl font-bold text-blue-900 mb-2">QR Code นำทาง</h3><div class="bg-white p-3 border-4 border-blue-50 rounded-2xl shadow-sm mb-4"><img src="${qrUrl}" alt="QR Code" class="w-48 h-48" /></div><p class="font-semibold text-gray-800 text-sm mb-1 line-clamp-1">${resource.name}</p><p class="text-xs text-gray-400">สแกนเพื่อเปิดแผนที่นำทาง (Google Maps)</p></div>`, showConfirmButton: true, confirmButtonText: 'ปิด', confirmButtonColor: '#1e3a8a', showCloseButton: true }); };
      return (
        <div className="space-y-6 animate-fade-in-up">
          <div className="bg-white p-6 rounded-3xl shadow-sm border border-purple-50 no-print flex flex-col gap-4">
            <div className="flex flex-col md:flex-row gap-4 items-end">
              <div className="flex-1 w-full"><label className="block text-xs font-bold text-purple-400 uppercase mb-1">เลือกพื้นที่อำเภอ</label><div className="relative"><select className="w-full appearance-none border-gray-200 rounded-2xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-3 bg-gray-50 text-sm font-medium transition-colors hover:bg-white border" value={filterDistrict} onChange={(e) => { setFilterDistrict(e.target.value); setFilterSubDistrict('all'); }}><option value="all">แสดงทุกอำเภอ</option>{KALASIN_LOCATIONS.map(d => <option key={d.district} value={d.district}>{d.district}</option>)}</select><div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-3 text-gray-500"><svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg></div></div></div>
              <div className="flex-1 w-full"><label className="block text-xs font-bold text-purple-400 uppercase mb-1">ศกร.ระดับตำบล</label><div className="relative"><select className="w-full appearance-none border-gray-200 rounded-2xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-3 bg-gray-50 text-sm font-medium transition-colors hover:bg-white border" value={filterSubDistrict} onChange={(e) => setFilterSubDistrict(e.target.value)} disabled={filterDistrict === 'all'}><option value="all">ทั้งหมด</option>{availableSubDistricts.map(s => <option key={s} value={s}>{s}</option>)}</select><div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-3 text-gray-500"><svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg></div></div></div>
              <button onClick={handlePrint} className="w-full md:w-auto bg-gradient-to-r from-amber-400 to-yellow-500 hover:from-amber-500 hover:to-yellow-600 text-purple-900 px-8 py-3 rounded-2xl shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2 font-bold text-sm border border-yellow-300"><IconPrinter size={20} /> พิมพ์รายงานทางการ</button>
            </div>
            <div className="relative"><IconSearch size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" /><input type="text" placeholder="🔍 ค้นหาชื่อแหล่งเรียนรู้..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full pl-11 pr-4 py-3 border border-gray-200 rounded-2xl bg-gray-50 text-sm font-medium focus:border-purple-500 focus:ring-purple-500 focus:bg-white transition-colors" /></div>
          </div>
          <div className="bg-white p-6 md:p-12 rounded-[2rem] shadow-xl shadow-gray-200/50 print:shadow-none print:w-full print:p-0 print:rounded-none border border-gray-100 print:border-none">
            <div className="hidden print:flex flex-row items-center gap-4 mb-4 pb-4 border-b border-gray-300"><img src={LOGO_URL} className="h-20 w-20 object-cover rounded-full border border-gray-200" alt="Logo" /><div className="text-left flex-1"><h1 className="text-xl font-bold text-black leading-tight">สรุปแผนที่แหล่งเรียนรู้ชุมชน Kalasin Learning T-Map</h1><h2 className="text-sm font-semibold text-gray-600 mt-1">สำนักงานส่งเสริมการเรียนรู้ประจำจังหวัดกาฬสินธุ์</h2><div className="mt-2 text-xs text-gray-500">ข้อมูล ณ วันที่: {new Date().toLocaleDateString('th-TH')} {filterDistrict !== 'all' ? `(เฉพาะ: ${filterDistrict})` : ''}</div></div></div>
            <div className="print:hidden flex flex-col items-center mb-8 text-center border-b border-gray-100 pb-8"><img src={LOGO_URL} alt="Logo" className="h-28 w-28 object-cover rounded-full mb-6 drop-shadow-xl border-4 border-white shadow-purple-200" /><h1 className="text-2xl md:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-800 to-indigo-800 print-text-primary mb-2">สรุปข้อมูลแหล่งเรียนรู้ชุมชน (Learning T-Map)</h1><h2 className="text-lg md:text-xl text-gray-500 font-semibold tracking-wide">สำนักงานส่งเสริมการเรียนรู้ประจำจังหวัดกาฬสินธ์ุ</h2><div className="mt-6 px-6 py-2 bg-purple-50 text-purple-900 rounded-full text-sm font-bold border border-purple-100 inline-block shadow-sm">ข้อมูล: {filterDistrict !== 'all' ? filterDistrict : 'ทุกอำเภอ'} {filterSubDistrict !== 'all' && ` - ${filterSubDistrict}`}</div></div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-10 no-print">
              <div className="bg-gradient-to-br from-purple-50 to-white p-8 rounded-3xl text-center border border-purple-100 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden"><div className="absolute top-0 right-0 p-4 opacity-10"><IconBarChart size={64} className="text-purple-500" /></div><h3 className="text-gray-500 font-bold mb-2 uppercase tracking-wider text-xs">ทั้งหมด</h3><p className="text-5xl md:text-6xl font-black text-purple-700 tracking-tighter">{filteredData.length}</p><p className="text-sm text-gray-400 mt-2 font-medium">แห่ง</p></div>
              {typeData.map((t) => (<div key={t.name} className="bg-white p-8 rounded-3xl text-center border border-gray-100 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group"><div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-transparent via-purple-400 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div><h3 className="text-gray-600 font-bold mb-2 truncate px-2 text-sm">{t.name}</h3><p className="text-4xl md:text-5xl font-extrabold text-gray-800">{t.value}</p><p className="text-sm text-gray-400 mt-2 font-medium">แห่ง</p></div>))}
            </div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12 break-inside-avoid no-print">
              <div className="h-96 w-full border border-gray-100 rounded-3xl p-6 shadow-sm bg-white"><h3 className="text-center font-bold text-gray-700 mb-6 text-lg flex items-center justify-center gap-2"><span className="w-2 h-2 rounded-full bg-purple-500"></span> สัดส่วนตามประเภท</h3><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={typeData} cx="50%" cy="50%" labelLine={true} label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`} outerRadius={90} fill="#8884d8" dataKey="value">{typeData.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}</Pie></PieChart></ResponsiveContainer></div>
              <div className="h-96 w-full border border-gray-100 rounded-3xl p-6 shadow-sm bg-white"><h3 className="text-center font-bold text-gray-700 mb-6 text-lg flex items-center justify-center gap-2"><span className="w-2 h-2 rounded-full bg-amber-500"></span> จำนวนแยกตามพื้นที่</h3><ResponsiveContainer width="100%" height="100%"><BarChart data={districtData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}><CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={true} stroke="#f0f0f0" /><XAxis type="number" allowDecimals={false} /><YAxis dataKey="name" type="category" width={100} style={{ fontSize: '0.7rem', fontWeight: 600, fill: '#6b7280' }} /><Bar dataKey="value" fill="#7c3aed" radius={[0, 6, 6, 0]} label={{ position: 'right', fill: '#6b7280', fontSize: 12, fontWeight: 600 }} barSize={20} /></BarChart></ResponsiveContainer></div>
            </div>
            {filterDistrict !== 'all' && subDistrictData.length > 0 && (<div className="mb-12 break-inside-avoid no-print"><div className="h-auto w-full border border-gray-100 rounded-3xl p-6 shadow-sm bg-white"><h3 className="text-center font-bold text-gray-700 mb-6 text-lg flex items-center justify-center gap-2"><span className="w-2 h-2 rounded-full bg-emerald-500"></span> จำนวนแยกตาม ศกร.ตำบล — {filterDistrict.replace('สกร.ระดับอำเภอ', '')}</h3><ResponsiveContainer width="100%" height={Math.max(200, subDistrictData.length * 35)}><BarChart data={subDistrictData} layout="vertical" margin={{ top: 5, right: 30, left: 60, bottom: 5 }}><CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" /><XAxis type="number" allowDecimals={false} /><YAxis dataKey="name" type="category" width={120} style={{ fontSize: '0.7rem', fontWeight: 600, fill: '#6b7280' }} /><Bar dataKey="value" fill="#10b981" radius={[0, 6, 6, 0]} label={{ position: 'right', fill: '#6b7280', fontSize: 12, fontWeight: 600 }} barSize={18} /></BarChart></ResponsiveContainer></div></div>)}
            <div className="mb-8 no-print"><button onClick={() => setShowComparison(!showComparison)} className={`w-full py-4 rounded-2xl font-bold text-sm border-2 transition-all flex items-center justify-center gap-2 ${showComparison ? 'bg-purple-600 text-white border-purple-600 shadow-lg shadow-purple-500/30' : 'bg-white text-purple-700 border-purple-200 hover:bg-purple-50'}`}><IconBarChart size={20} /> {showComparison ? '🔼 ซ่อนตารางเปรียบเทียบ' : '📊 แสดงตารางเปรียบเทียบข้อมูลระหว่างอำเภอ'}</button></div>
            {showComparison && (<div className="mb-12 overflow-hidden rounded-3xl border border-purple-200 shadow-lg no-print animate-fade-in-up"><div className="bg-gradient-to-r from-purple-600 to-indigo-600 px-6 py-4"><h3 className="text-white font-bold text-lg flex items-center gap-2">📊 เปรียบเทียบข้อมูลระหว่างอำเภอ</h3></div><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-sm"><thead className="bg-purple-50"><tr><th className="px-4 py-3 text-left font-bold text-purple-900 text-xs">อำเภอ</th><th className="px-4 py-3 text-center font-bold text-purple-900 text-xs">ทั้งหมด</th><th className="px-4 py-3 text-center font-bold text-purple-900 text-xs">บุคคล</th><th className="px-4 py-3 text-center font-bold text-purple-900 text-xs">สื่อ/นวัตกรรม</th><th className="px-4 py-3 text-center font-bold text-purple-900 text-xs">สถานที่</th><th className="px-4 py-3 text-center font-bold text-purple-900 text-xs">ตำบลที่ครอบคลุม</th></tr></thead><tbody className="bg-white divide-y divide-gray-100">{comparisonData.map((d, idx) => (<tr key={d.name} className={`hover:bg-purple-50/50 transition-colors ${idx === 0 ? 'bg-amber-50/50' : ''}`}><td className="px-4 py-3 font-bold text-gray-800 flex items-center gap-2">{idx === 0 && <span className="text-amber-500">🏆</span>}{d.name}</td><td className="px-4 py-3 text-center font-extrabold text-purple-700 text-lg">{d.total}</td><td className="px-4 py-3 text-center text-gray-600">{d.person}</td><td className="px-4 py-3 text-center text-gray-600">{d.innovation}</td><td className="px-4 py-3 text-center text-gray-600">{d.place}</td><td className="px-4 py-3 text-center"><span className={`px-2 py-1 rounded-full text-xs font-bold ${d.coverage === d.subDistrictCount ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>{d.coverage}/{d.subDistrictCount}</span></td></tr>))}</tbody></table></div></div>)}
            <div className="overflow-hidden rounded-3xl border border-gray-200 shadow-sm print:rounded-none print:border-none">
              <table className="min-w-full divide-y divide-gray-100 text-sm">
                <thead className="bg-white print:bg-gray-100 print:text-black"><tr><th className="px-4 py-3 text-center font-bold text-gray-700 w-[5%] uppercase tracking-wider text-xs bg-gray-50/50 print:border-b print:border-gray-300">ลำดับ</th><th className="px-4 py-3 text-center font-bold text-gray-700 w-[45%] uppercase tracking-wider text-xs bg-gray-50/50 print:border-b print:border-gray-300">ชื่อแหล่งเรียนรู้</th><th className="px-4 py-3 text-center font-bold text-gray-700 w-[20%] hidden md:table-cell print:table-cell uppercase tracking-wider text-xs bg-gray-50/50 print:border-b print:border-gray-300">ประเภท</th><th className="px-4 py-3 text-center font-bold text-gray-700 w-[10%] uppercase tracking-wider text-xs bg-gray-50/50 print:border-b print:border-gray-300 no-print">การเข้าถึง</th><th className="px-4 py-3 text-center font-bold text-gray-700 w-[30%] uppercase tracking-wider text-xs bg-gray-50/50 print:border-b print:border-gray-300">ที่ตั้ง (ตำบล, อำเภอ)</th></tr></thead>
                <tbody className="bg-white divide-y divide-gray-100">
                  {currentItems.map((item, idx) => (<tr key={item.id} className="group hover:bg-purple-50/50 transition-colors print:break-inside-avoid"><td className="px-4 py-3 text-center text-gray-500 font-mono group-hover:text-purple-600 font-medium print:border-b print:border-gray-200 print:text-black">{isPrinting ? idx + 1 + indexOfFirstItem : indexOfFirstItem + idx + 1}</td><td className="px-4 py-3 font-semibold text-gray-800 group-hover:text-purple-900 print:border-b print:border-gray-200 print:text-black">{item.name}<div className="md:hidden print:hidden text-xs text-purple-500 mt-1 font-normal bg-purple-50 inline-block px-2 py-0.5 rounded-md border border-purple-100">{item.type.replace('แหล่งเรียนรู้ประเภท', '')}</div></td><td className="px-4 py-3 text-center text-gray-600 hidden md:table-cell print:table-cell print:border-b print:border-gray-200 print:text-black"><span className="px-3 py-1 bg-gray-100 text-gray-600 rounded-full text-xs font-medium border border-gray-200 group-hover:bg-white group-hover:shadow-sm transition-all print:bg-transparent print:border-none print:shadow-none print:p-0">{item.type.replace('แหล่งเรียนรู้ประเภท', '')}</span></td><td className="px-4 py-3 text-center no-print"><div className="flex justify-center gap-2"><button onClick={() => handleShare(item)} className="p-2 text-indigo-600 hover:bg-indigo-100 rounded-xl transition-all border border-indigo-50 active:scale-90" title="แชร์พิกัด"><IconShare2 size={16} /></button><button onClick={() => showQRCode(item)} className="p-2 text-amber-600 hover:bg-amber-100 rounded-xl transition-all border border-amber-50 active:scale-90" title="QR Code"><IconQrCode size={16} /></button></div></td><td className="px-4 py-3 text-left text-gray-500 group-hover:text-gray-700 print:border-b print:border-gray-200 print:text-black">{item.subDistrict}, <br className="md:hidden print:hidden" />{item.district.replace('สกร.ระดับอำเภอ', '')}</td></tr>))}
                  {currentItems.length === 0 && <tr><td colSpan="5" className="px-6 py-16 text-center text-gray-400 bg-gray-50/30">ไม่พบข้อมูล</td></tr>}
                </tbody>
              </table>
            </div>
            {!isPrinting && totalPages > 1 && (<div className="flex items-center justify-center gap-3 p-5 bg-gray-50 border-t border-gray-200 no-print"><button onClick={() => goToPage(currentPage - 1)} disabled={currentPage === 1} className="p-2.5 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 disabled:opacity-50 shadow-sm transition-all hover:border-purple-300 text-gray-600"><IconChevronLeft size={20} /></button><span className="text-sm font-bold text-gray-700 px-4 bg-white py-2 rounded-xl border border-gray-200 shadow-sm">หน้า {currentPage} / {totalPages}</span><button onClick={() => goToPage(currentPage + 1)} disabled={currentPage === totalPages} className="p-2.5 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 disabled:opacity-50 shadow-sm transition-all hover:border-purple-300 text-gray-600"><IconChevronRight size={20} /></button></div>)}
          </div>
        </div>
      );
    };
    // 4.4 AdminTab (แก้ไข: อัพโหลดรูปไป Google Drive แทนเก็บ Base64)

export default DashboardTab;