import React, { useState, useEffect, useMemo, useRef } from "react";
import { IconFilter, IconChevronDown, IconShare2, ResourceType, KALASIN_LOCATIONS, MARKER_COLORS, createColoredMarkerIcon } from "../constants";
import L from "leaflet";
import Swal from "sweetalert2";

    const MapTab = ({ resources }) => {
      const mapContainerRef = useRef(null);
      const mapInstanceRef = useRef(null);
      const markersRef = useRef([]);
      const [filterType, setFilterType] = useState('all');
      const [filterDistrict, setFilterDistrict] = useState('all');
      const [filteredResources, setFilteredResources] = useState(resources);
      const [showFilters, setShowFilters] = useState(false);
      useEffect(() => { delete L.Icon.Default.prototype._getIconUrl; L.Icon.Default.mergeOptions({ iconRetinaUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon-2x.png', iconUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png', shadowUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-shadow.png' }); }, []);
      useEffect(() => { let temp = resources; if (filterType !== 'all') temp = temp.filter(r => r.type === filterType); if (filterDistrict !== 'all') temp = temp.filter(r => r.district === filterDistrict); setFilteredResources(temp); }, [filterType, filterDistrict, resources]);
      const displayResources = useMemo(() => { const positionCounts = {}; return filteredResources.map(r => { const key = `${r.latitude},${r.longitude}`; const offsetIndex = positionCounts[key] || 0; positionCounts[key] = offsetIndex + 1; let displayLat = Number(r.latitude); let displayLng = Number(r.longitude); if (offsetIndex > 0) { const radius = 0.00025 * (1 + Math.floor(offsetIndex / 8)); const angle = (offsetIndex % 8) * (Math.PI / 4); displayLat += radius * Math.sin(angle); displayLng += radius * Math.cos(angle); } return { ...r, displayLat, displayLng }; }); }, [filteredResources]);
      useEffect(() => { if (!mapContainerRef.current) return; if (mapInstanceRef.current) return; const map = L.map(mapContainerRef.current).setView([16.4322, 103.5061], 9); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap' }).addTo(map); mapInstanceRef.current = map; return () => { if (mapInstanceRef.current) { mapInstanceRef.current.remove(); mapInstanceRef.current = null; } }; }, []);
      useEffect(() => {
        if (!mapInstanceRef.current) return;
        markersRef.current.forEach(marker => marker.remove());
        markersRef.current = [];
        displayResources.forEach(r => {
          const marker = L.marker([r.displayLat, r.displayLng], { icon: createColoredMarkerIcon(r.type) }).addTo(mapInstanceRef.current);
          const popupContent = document.createElement('div');
          const googleMapsUrl = `https://www.google.com/maps?q=${r.latitude},${r.longitude}`;
          popupContent.innerHTML = `<div class="p-1 min-w-[220px] font-sans"><h3 class="font-bold text-purple-900 text-lg mb-2 leading-tight border-b border-purple-100 pb-2">${r.name}</h3>${r.imageUrl ? `<img src="${fixDriveImageUrl(r.imageUrl)}" crossorigin="anonymous" class="w-full h-40 object-cover rounded-xl mb-3 shadow-md border border-gray-100" onerror="this.style.display='none'" />` : ''}<div class="text-xs text-gray-500 mb-2 flex items-center gap-1">📍 ${r.subDistrict}, ${r.district}</div><span class="text-xs bg-purple-100 text-purple-800 px-3 py-1 rounded-full border border-purple-200 inline-block mb-3 font-semibold shadow-sm">${r.type.replace('แหล่งเรียนรู้ประเภท', '')}</span><p class="text-sm mb-3 text-gray-700 line-clamp-3 bg-gray-50 p-2 rounded-lg border border-gray-100">${r.description || '-'}</p>${r.contactInfo ? `<p class="text-sm font-semibold text-green-700 mb-3 flex items-center gap-1 bg-green-50 p-2 rounded-lg border border-green-100">📞 ${r.contactInfo}</p>` : ''}<div class="grid grid-cols-3 gap-2 mt-2"><button id="btn-share-${r.id}" class="bg-amber-500 text-white p-2 rounded-lg text-[10px] flex items-center justify-center gap-1 font-bold shadow-sm w-full">แชร์พิกัด</button><button id="btn-qr-${r.id}" class="bg-blue-600 text-white p-2 rounded-lg text-[10px] flex items-center justify-center gap-1 font-bold shadow-sm w-full">QR Code</button><a href="${googleMapsUrl}" target="_blank" class="bg-purple-700 text-white p-2 rounded-lg text-[10px] flex items-center justify-center gap-1 font-bold shadow-sm w-full no-underline">นำทาง</a></div></div>`;
          marker.bindPopup(popupContent).on('popupopen', () => { const btnShare = document.getElementById(`btn-share-${r.id}`); if (btnShare) { btnShare.onclick = () => handleShareResource(r); } const btnQr = document.getElementById(`btn-qr-${r.id}`); if (btnQr) { btnQr.onclick = () => showQRCode(r); } });
          markersRef.current.push(marker);
        });
      }, [displayResources]);
      const handleShareResource = (r) => { const googleMapsUrl = `https://www.google.com/maps/search/?api=1&query=${r.latitude},${r.longitude}`; const text = `แนะนำแหล่งเรียนรู้: ${r.name}\n📍 ${r.subDistrict}, ${r.district}`; if (navigator.share) { navigator.share({ title: 'Kalasin Learning T-Map', text: text, url: googleMapsUrl }).catch(console.error); } else { Swal.fire({ title: 'แชร์พิกัดนำทาง', html: `<div class="p-2 space-y-4"><button onclick="navigator.clipboard.writeText('${googleMapsUrl}'); Swal.fire('คัดลอกลิงก์แผนที่แล้ว','','success')" class="w-full bg-purple-700 text-white p-3 rounded-xl font-bold shadow-lg">คัดลอกลิงก์ Google Maps</button></div>`, showConfirmButton: false, showCloseButton: true }); } };
      const showQRCode = (resource) => { const googleMapsUrl = `https://www.google.com/maps/search/?api=1&query=${resource.latitude},${resource.longitude}`; const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(googleMapsUrl)}`; Swal.fire({ html: `<div class="flex flex-col items-center pt-2"><h3 class="text-xl font-bold text-blue-900 mb-2">QR Code นำทาง</h3><div class="bg-white p-3 border-4 border-blue-50 rounded-2xl shadow-sm mb-4"><img src="${qrUrl}" alt="QR Code" class="w-48 h-48" /></div><p class="font-semibold text-gray-800 text-sm mb-1 line-clamp-1">${resource.name}</p><p class="text-xs text-gray-400">สแกนเพื่อเปิดแผนที่นำทาง (Google Maps)</p></div>`, showConfirmButton: true, confirmButtonText: 'ปิด', confirmButtonColor: '#1e3a8a', showCloseButton: true }); };
      const handleShareApp = () => { const url = "https://script.google.com/macros/s/AKfycbzrhGl2CR5ZumRpgbG0KAcAlOnpwVclyaAcSluGq7YLutuSu8USYpreK7yDBa4nbdqi/exec"; const text = 'Kalasin Learning T-Map: ระบบสารสนเทศภูมิศาสตร์แหล่งเรียนรู้ชุมชน'; if (navigator.share) { navigator.share({ title: 'Kalasin Learning T-Map', text: text, url: url }).catch(console.error); } else { Swal.fire({ title: 'แชร์ระบบสารสนเทศ', html: `<div class="p-2 space-y-4"><button onclick="navigator.clipboard.writeText('${url}'); Swal.fire('คัดลอกลิงก์แล้ว','','success')" class="w-full bg-purple-700 text-white p-3 rounded-xl font-bold shadow-lg">คัดลอกลิงก์</button></div>`, showConfirmButton: false, showCloseButton: true }); } };
      return (
        <div className="flex flex-col h-[calc(100vh-180px)] lg:h-[calc(100vh-160px)] gap-3 lg:gap-6">
          <div className="lg:hidden bg-white p-3 rounded-2xl shadow-md border border-purple-50 flex items-center justify-between gap-2">
            <button onClick={() => setShowFilters(!showFilters)} className="flex items-center gap-2 text-sm font-bold text-purple-800 bg-purple-50 px-4 py-2.5 rounded-xl border border-purple-200 active:scale-95 transition-all flex-shrink-0"><IconFilter size={16} /> ตัวกรอง <span className={`transform transition-transform duration-200 ${showFilters ? 'rotate-180' : ''}`}><IconChevronDown size={16} /></span></button>
            <button onClick={handleShareApp} className="bg-white border border-purple-200 text-purple-700 px-3 py-2.5 rounded-xl font-bold shadow-sm hover:bg-purple-50 flex items-center gap-1.5 text-xs flex-shrink-0"><IconShare2 size={14} /> แชร์</button>
            <div className="bg-purple-100 px-3 py-2 rounded-xl border border-purple-200 flex items-center flex-shrink-0"><span className="font-extrabold text-purple-700 text-lg mr-1">{filteredResources.length}</span><span className="text-purple-600 font-medium text-xs">แห่ง</span></div>
          </div>
          {showFilters && (<div className="lg:hidden bg-white p-4 rounded-2xl shadow-md border border-purple-50 animate-fade-in-up space-y-3"><div><label className="block text-xs font-bold text-purple-900 mb-1">ประเภทแหล่งเรียนรู้</label><select value={filterType} onChange={(e) => setFilterType(e.target.value)} className="w-full appearance-none border-gray-200 rounded-xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-2.5 bg-gray-50 text-sm font-medium border"><option value="all">ทั้งหมด</option>{Object.values(ResourceType).map(t => <option key={t} value={t}>{t}</option>)}</select></div><div><label className="block text-xs font-bold text-purple-900 mb-1">พื้นที่ (สกร.อำเภอ)</label><select value={filterDistrict} onChange={(e) => setFilterDistrict(e.target.value)} className="w-full appearance-none border-gray-200 rounded-xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-2.5 bg-gray-50 text-sm font-medium border"><option value="all">ทั้งหมด</option>{KALASIN_LOCATIONS.map(d => <option key={d.district} value={d.district}>{d.district}</option>)}</select></div></div>)}
          <div className="hidden lg:grid bg-white p-5 lg:p-6 rounded-3xl shadow-xl shadow-purple-900/5 border border-purple-50 grid-cols-3 gap-5">
            <div><label className="block text-sm font-bold text-purple-900 mb-2">ประเภทแหล่งเรียนรู้</label><select value={filterType} onChange={(e) => setFilterType(e.target.value)} className="w-full appearance-none border-gray-200 rounded-2xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-3 bg-gray-50 text-sm font-medium transition-colors hover:bg-white border"><option value="all">ทั้งหมด</option>{Object.values(ResourceType).map(t => <option key={t} value={t}>{t}</option>)}</select></div>
            <div><label className="block text-sm font-bold text-purple-900 mb-2">พื้นที่ (สกร.อำเภอ)</label><select value={filterDistrict} onChange={(e) => setFilterDistrict(e.target.value)} className="w-full appearance-none border-gray-200 rounded-2xl shadow-sm focus:border-purple-500 focus:ring-purple-500 p-3 bg-gray-50 text-sm font-medium transition-colors hover:bg-white border"><option value="all">ทั้งหมด</option>{KALASIN_LOCATIONS.map(d => <option key={d.district} value={d.district}>{d.district}</option>)}</select></div>
            <div className="flex items-end justify-end pb-1 text-sm text-gray-500 gap-2"><button onClick={handleShareApp} className="bg-white border border-purple-200 text-purple-700 px-4 py-2 rounded-2xl font-bold shadow-sm hover:bg-purple-50 flex items-center gap-2 h-[46px]"><IconShare2 size={18} /> แชร์หน้านี้</button><div className="bg-purple-100 px-4 py-2 rounded-2xl border border-purple-200 h-[46px] flex items-center"><span className="font-extrabold text-purple-700 text-2xl mr-1">{filteredResources.length}</span> <span className="text-purple-600 font-medium">แห่ง</span></div></div>
          </div>
          <div className="flex-grow rounded-3xl overflow-hidden shadow-2xl border-4 border-white relative ring-1 ring-black/5">
            <div ref={mapContainerRef} style={{ width: '100%', height: '100%' }}></div>
            <div className="absolute bottom-3 left-3 z-[1000] bg-white/95 backdrop-blur-sm rounded-xl shadow-lg border border-gray-200" style={{ pointerEvents: 'auto' }}>
              <div className="px-3 py-2 hidden lg:block"><div className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1.5">คำอธิบายสัญลักษณ์</div><div className="space-y-1">{Object.entries(MARKER_COLORS).map(([key, val]) => (<div key={key} className="flex items-center gap-2"><span className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: val.fill }}></span><span className="text-xs text-gray-700 font-medium whitespace-nowrap">{val.label}</span></div>))}</div></div>
              <div className="px-2.5 py-1.5 lg:hidden flex items-center gap-3">{Object.entries(MARKER_COLORS).map(([key, val]) => (<div key={key} className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full flex-shrink-0" style={{ backgroundColor: val.fill }}></span><span className="text-[10px] text-gray-600 font-semibold whitespace-nowrap">{val.label.split(' ')[0]}</span></div>))}</div>
            </div>
          </div>
        </div>
      );
    };
    // 4.3 DashboardTab

export default MapTab;